language: ruby
cache: bundler
install:
  - bundle install
build:
  - jekyll build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "frontendian-production"
  local_dir: _site