title: the frontendian
email: ryan@frontendian.co
description:
  en: A little blog about building web applications. Posts arrive weekly on performance, security, accessibility, tooling, and more.
  pt_BR: Um blog simples sobre construção de aplicações web. Posts toda semana sobre performance, segurança, acessibilidade, ferramentas e mais.
url: "https://frontendian.co"
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jekyll-feed
  - jekyll-polyglot
languages: ["en", "pt_BR"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

# Language Vars
latest_post:
  en: Latest Post
  pt_BR: Último Post
recent_posts:
  en: Recent Posts
  pt_BR: Posts Recentes

buttons:
  keep_reading:
    en: Keep Reading
    pt_BR: Continuar Lendo
  read_more:
    en: Read More
    pt_BR: Leia Mais

footer:
  made_with_and_by:
    en: Made with ☕ in Seattle by
    pt_BR: Feito com ☕ em Seattle por
  translated_by:
    pt_BR: Traduzido para o Português Brasileiro por <a href="http://heitorfig.com/" target="_blank">Heitor Figueiredo</a>.