title: The Frontendian
email: ryan@frontendian.co
description: A little blog about building web applications.
url: "https://frontendian.co"
permalink: /:categories/:title
markdown: kramdown
include: ['_translations']
plugins:
  - jekyll-feed