title: The Frontendian
email: ryan@frontendian.co
description: A little blog about building web applications.
url: "https://frontendian.co"
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jekyll-feed